server:
  port: 5000
  error:
    include-message: always
  forward-headers-strategy: framework

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://szt.cvgdaih6dhcu.eu-central-1.rds.amazonaws.com:3306/szt?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: NFHNI>|bdUjbx$0L
    #url: jdbc:mysql://localhost:3306/szt-ecommerce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    #username: root
    #password: 12345678
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


contact:
  email: szt.sylwia.mieszkowska@gmail.com